

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.yuzdeButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.bas("%"))
        self.yuzdeButton.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.yuzdeButton.setFont(font)
        self.yuzdeButton.setObjectName("yuzdeButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("C"))
        self.cButton.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.okButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.sil())
        self.okButton.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.bolmeButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("/"))
        self.bolmeButton.setGeometry(QtCore.QRect(280, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.bolmeButton.setFont(font)
        self.bolmeButton.setObjectName("bolmeButton")
        self.yediButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("7"))
        self.yediButton.setGeometry(QtCore.QRect(10, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.yediButton.setFont(font)
        self.yediButton.setObjectName("yediButton")
        self.dokuzButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("9"))
        self.dokuzButton.setGeometry(QtCore.QRect(190, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dokuzButton.setFont(font)
        self.dokuzButton.setObjectName("dokuzButton")
        self.sekizButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("8"))
        self.sekizButton.setGeometry(QtCore.QRect(100, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sekizButton.setFont(font)
        self.sekizButton.setObjectName("sekizButton")
        self.carpmaButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("*"))
        self.carpmaButton.setGeometry(QtCore.QRect(280, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.carpmaButton.setFont(font)
        self.carpmaButton.setObjectName("carpmaButton")
        self.dortButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("4"))
        self.dortButton.setGeometry(QtCore.QRect(10, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dortButton.setFont(font)
        self.dortButton.setObjectName("dortButton")
        self.altiButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("6"))
        self.altiButton.setGeometry(QtCore.QRect(190, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.altiButton.setFont(font)
        self.altiButton.setObjectName("altiButton")
        self.besButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("5"))
        self.besButton.setGeometry(QtCore.QRect(100, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.besButton.setFont(font)
        self.besButton.setObjectName("besButton")
        self.cikarmaButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("-"))
        self.cikarmaButton.setGeometry(QtCore.QRect(280, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cikarmaButton.setFont(font)
        self.cikarmaButton.setObjectName("cikarmaButton")
        self.birButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("1"))
        self.birButton.setGeometry(QtCore.QRect(10, 350, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.birButton.setFont(font)
        self.birButton.setObjectName("birButton")
        self.ucButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("3"))
        self.ucButton.setGeometry(QtCore.QRect(190, 350, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ucButton.setFont(font)
        self.ucButton.setObjectName("ucButton")
        self.ikiButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("2"))
        self.ikiButton.setGeometry(QtCore.QRect(100, 350, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ikiButton.setFont(font)
        self.ikiButton.setObjectName("ikiButton")
        self.toplamaButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("+"))
        self.toplamaButton.setGeometry(QtCore.QRect(280, 350, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.toplamaButton.setFont(font)
        self.toplamaButton.setObjectName("toplamaButton")
        self.artieksiButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.arti_eksi())
        self.artieksiButton.setGeometry(QtCore.QRect(10, 430, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.artieksiButton.setFont(font)
        self.artieksiButton.setObjectName("artieksiButton")
        self.noktaButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.noktala())
        self.noktaButton.setGeometry(QtCore.QRect(190, 430, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.noktaButton.setFont(font)
        self.noktaButton.setObjectName("noktaButton")
        self.sifirButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.bas("0"))
        self.sifirButton.setGeometry(QtCore.QRect(100, 430, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sifirButton.setFont(font)
        self.sifirButton.setObjectName("sifirButton")
        self.esittirButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.mat())
        self.esittirButton.setGeometry(QtCore.QRect(280, 430, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.esittirButton.setFont(font)
        self.esittirButton.setObjectName("esittirButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def arti_eksi(self):
        screen = self.outputLabel.text()
        if "-" in screen:
            self.outputLabel.setText(screen.replace("-", ""))
        else:
             self.outputLabel.setText(f'-{screen}')

    def mat(self):
        screen = self.outputLabel.text()
        try:
            answer = eval(screen)
            self.outputLabel.setText(str(answer))
        except:
            self.outputLabel.setText(str("Hata!"))



    def sil(self):
        screen = self.outputLabel.text()
        screen = screen[:-1]
        self.outputLabel.setText(screen)


    def noktala(self):
        screen = self.outputLabel.text()
        if screen[-1]==".":
            pass
        else:
            self.outputLabel.setText(f'{screen}.')


    def bas(self,basildi):
        if basildi=="C":
            self.outputLabel.setText("0")
        else:
            if self.outputLabel.text() == "0":
             self.outputLabel.setText("")    
            
            self.outputLabel.setText(f'{self.outputLabel.text()}{basildi}')
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.yuzdeButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.okButton.setText(_translate("MainWindow", "<<"))
        self.bolmeButton.setText(_translate("MainWindow", "/"))
        self.yediButton.setText(_translate("MainWindow", "7"))
        self.dokuzButton.setText(_translate("MainWindow", "9"))
        self.sekizButton.setText(_translate("MainWindow", "8"))
        self.carpmaButton.setText(_translate("MainWindow", "x"))
        self.dortButton.setText(_translate("MainWindow", "4"))
        self.altiButton.setText(_translate("MainWindow", "6"))
        self.besButton.setText(_translate("MainWindow", "5"))
        self.cikarmaButton.setText(_translate("MainWindow", "-"))
        self.birButton.setText(_translate("MainWindow", "1"))
        self.ucButton.setText(_translate("MainWindow", "3"))
        self.ikiButton.setText(_translate("MainWindow", "2"))
        self.toplamaButton.setText(_translate("MainWindow", "+"))
        self.artieksiButton.setText(_translate("MainWindow", "+/-"))
        self.noktaButton.setText(_translate("MainWindow", "."))
        self.sifirButton.setText(_translate("MainWindow", "0"))
        self.esittirButton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
